yatube/about/urls.py
from django.urls import path

from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "group/<slug:slug>/",
        views.GroupPostsView.as_view(),
        name="group_list"
    ),
    path(
        "profile/<str:username>/",
        views.ProfileView.as_view(),
        name="profile"
    ),
    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail"
    ),
    path(
        "posts/<int:post_id>/edit/",
        views.PostEditView.as_view(),
        name="post_edit"
    ),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/comment/",
        views.AddCommentView.as_view(),
        name="add_comment"
    ),
    path("follow/", views.FollowIndexView.as_view(), name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.ProfileFollowView.as_view(),
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.ProfileUnfollowView.as_view(),
        name="profile_unfollow",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    from django.urls import include

    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

yatube/templates/includes/footer.html
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/forms_make.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

<form method="post" enctype="multipart/form-data"
        {% if action_url %} action="{% url action_url %}" {% endif %}>
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group row my-3"
            {% if field.field.required %}
         aria-required="true"
            {% else %}
         aria-required="false"
            {% endif %}
    >
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
      </label>
      <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    </div>
  {% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href={% url "posts:index" %}>
      {% load static %}
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
           href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
             href="{% url 'posts:post_create' %}">
            Новая запись
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
             href="{% url 'users:password_change' %}">
            Изменить пароль
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
             href="{% url 'users:logout' %}">
            Выйти
          </a>
        </li>
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:profile' %}active{% endif %}"
               href="/profile/{{ user.username }}">
              Пользователь: {{ user.username }}
            </a>
          </li>
        {% endwith %}
        <li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
           href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
           href="{% url 'users:signup' %}">
          Регистрация
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}