yatube/about/urls.py
from django.urls import path

from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "group/<slug:slug>/",
        views.GroupPostsView.as_view(),
        name="group_list"
    ),
    path(
        "profile/<str:username>/",
        views.ProfileView.as_view(),
        name="profile"
    ),
    path(
        "posts/<int:post_id>/",
        views.PostDetailView.as_view(),
        name="post_detail"
    ),
    path(
        "posts/<int:post_id>/edit/",
        views.PostEditView.as_view(),
        name="post_edit"
    ),
    path("create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "posts/<int:post_id>/comment/",
        views.AddCommentView.as_view(),
        name="add_comment"
    ),
    path("follow/", views.FollowIndexView.as_view(), name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.ProfileFollowView.as_view(),
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.ProfileUnfollowView.as_view(),
        name="profile_unfollow",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    from django.urls import include

    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import models
from django.urls import reverse

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название группы")
    slug = models.SlugField(unique=True, verbose_name="URL")
    description = models.TextField(verbose_name="Описание группы")

    class Meta:
        verbose_name = "Группа сообщества"
        verbose_name_plural = "Группы сообщества"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts", kwargs={"slug": self.slug})


class Post(CreatedModel):
    text = models.TextField(
        verbose_name="Текст поста", help_text="Введите текст поста"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите сообщество",
    )
    image = models.ImageField(
        "Картинка",
        upload_to="posts/",
        blank=True,
        help_text="Загрузите картинку",
    )

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[: settings.NUMS_OF_SYMBOLS_POST_TEXT]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name="Ссылка на пост",
        related_name="comments",
        help_text="Комментарии к конкретному посту",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField(
        verbose_name="Текст комментария", help_text="Введите комментарий поста"
    )

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Подписка автора",
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {
            "text": "Текст сообщения",
            "group": "Сообщество",
            "image": "Картинки поста",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": "Текст комментария"}

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from posts.forms import CommentForm, PostForm
from posts.models import Comment, Follow, Group, Post, User


class IndexView(ListView):
    template_name = "posts/index.html"
    paginate_by = settings.NUMS_OF_POSTS_ON_PAGE
    model = Post

    def get_queryset(self):
        return self.model.objects.prefetch_related("author", "group")


class GroupPostsView(ListView):
    model = Group
    paginate_by = settings.NUMS_OF_POSTS_ON_PAGE
    template_name = "posts/group_list.html"

    def get_queryset(self):
        return get_object_or_404(
            self.model,
            slug=self.kwargs.get('slug')
        ).posts.select_related("author")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = get_object_or_404(
            self.model,
            slug=self.kwargs.get('slug')
        )
        return context


class ProfileView(ListView):
    model = Post
    paginate_by = settings.NUMS_OF_POSTS_ON_PAGE
    template_name = "posts/profile.html"
    user = None

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.user = request.user
        return super().dispatch(request, **kwargs)

    def get_queryset(self):
        return get_object_or_404(
            User, username=self.kwargs.get('username')
        ).posts.prefetch_related("group")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(
            User,
            username=self.kwargs.get('username')
        )
        context["author"] = get_object_or_404(
            User,
            username=self.kwargs.get('username')
        )
        context["following"] = Follow.objects.filter(
            user=self.user,
            author=author
        ).exists()
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = 'post'
    pk_url_kwarg = "post_id"

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data()
        context["count"] = self.model.objects.filter(
            author=context["post"].author
        ).count()
        context["comments"] = Comment.objects.filter(
            post=context['post']
        ).all()
        context["form_comment"] = CommentForm()
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = "posts/create_post.html"
    context_object_name = "form"
    form_class = PostForm
    context = {}

    def post(self, request, *args, **kwargs):
        form = self.form_class(
            request.POST or None,
            files=request.FILES or None
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:profile", request.user)
        self.context["form"] = form
        return render(request, self.template_name, self.context)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    pk_url_kwarg = "post_id"
    template_name = "posts/create_post.html"
    context_object_name = "post"
    context = {}

    def dispatch(self, request, *args, **kwargs):
        obj = super().get_object()
        if request.user != obj.author:
            return redirect(
                "posts:post_edit",
                post_id=self.kwargs['post_id']
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse(
            "posts:post_detail", kwargs={"post_id": self.kwargs["post_id"]}
        )


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    pk_url_kwarg = "post_id"
    template_name = "posts/post_detail.html"
    form_class = CommentForm
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["count"] = self.model.objects.filter(
            author=context["post"].author
        ).count()
        context["comments"] = Comment.objects.filter(
            post=context['post']
        ).all()
        context["form_comment"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=self.kwargs["post_id"])
        comment.save()
        return redirect("posts:post_detail", post_id=self.kwargs["post_id"])


class FollowIndexView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = settings.NUMS_OF_POSTS_ON_PAGE
    user = None
    template_name = "posts/follow.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.user = request.user
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(author__following__user=self.user)


class ProfileFollowView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        author = get_object_or_404(User, username=self.kwargs["username"])
        if request.user != author:
            Follow.objects.get_or_create(user=request.user, author=author)
        return redirect("posts:profile", username=self.kwargs["username"])


class ProfileUnfollowView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        author = get_object_or_404(User, username=self.kwargs["username"])
        if request.user != author:
            Follow.objects.filter(user=request.user, author=author).delete()
        return redirect("posts:profile", username=self.kwargs["username"])

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if not post %}
    Добавить запись
  {% else %}
    Редактировать запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if not post %}
            Добавить запись
            {% else %}
            Редактировать запись
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/forms_make.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                {% if post %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% if not forloop.last %}<hr>{% endif %}
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Посты, на которые подписан {{ user.username }}
{% endblock %}
{% block header %}
  Посты, на которые подписан {{ user.username }}
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% include 'posts/includes/posts.html' %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block header %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <h1> Записи сообщества: {{ group.title }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    <article>
      <h3>
        Автор: {{ post.author.get_full_name }},
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </h3>
      {% if post.image %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      {% endif %}
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block header %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% load cache %}
  {% cache 20 index_page %}
    {% include 'posts/includes/switcher.html' %}
    {% include 'posts/includes/posts.html' %}
    {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
  {% load thumbnail %}
  {% load user_filters %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <p>
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </p>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: @{{ post.author.get_full_name }}
          </li>
          <li class=
                      "list-group-item
                      d-flex justify-content-between align-items-center">
            Всего постов автора: {{ count }}
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      {% if post.image %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      {% endif %}
      <article class="col-12 col-md-9">
        <p>{{ post.text }}</p>
      </article>
    </div>
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">{{ form_comment.text|addclass:"form-control" }}</div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </main>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock title %}
{% block header %}
  Профайл пользователя
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
    {% if following %}
      <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
        Подписаться
      </a>
    {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% if post.image %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      {% endif %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_edit' post.id %}">редактировать пост</a><br>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы {{ post.group }}
      </a>
    {% endif %}
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}